SET NAMES UTF8;
DROP DATABASE IF EXISTS hd;
CREATE DATABASE hd CHARSET=UTF8;
USE hd;
CREATE TABLE hd_user(
  uid INT PRIMARY KEY AUTO_INCREMENT,
  uname VARCHAR(32),
  upwd VARCHAR(32),
  email VARCHAR(64),
  phone CHAR(16),
  avatar VARCHAR(128),
  user_name VARCHAR(16),
  gender INT 
);